# HTTP Status Codes
HTTP_OK = 200
HTTP_CREATED = 201
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_PAYMENT_REQUIRED = 402
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_INTERNAL_SERVER_ERROR = 500
HTTP_RATE_LIMITED = 429

# Shopify API
SHOPIFY_API_VERSION = "2026-01"
MAX_RATE_LIMIT_RETRIES = 3

# API Limits
PRODUCT_PAGE_LIMIT = 250
ORDER_PAGE_LIMIT = 250
INVENTORY_BATCH_SIZE = 50

# Timeouts (seconds)
IMAGE_DOWNLOAD_TIMEOUT = 15
API_REQUEST_TIMEOUT = 30

# Pagination Defaults
DEFAULT_IMAGE_POSITION = 999
DEFAULT_VARIANT_SEARCH_LIMIT = 1
DEFAULT_CATEGORY_SEARCH_LIMIT = 1
DEFAULT_PARTNER_SEARCH_LIMIT = 1
DEFAULT_COUNTRY_SEARCH_LIMIT = 1
DEFAULT_STATE_SEARCH_LIMIT = 1
